import json, os, sys

data = json.load(open('/tmp/result.json'))
date = data['date']
briefing = data['briefing']
model = data.get('model', 'unknown')
path = f"/tmp/tr/memory/daily/{date}.md"

os.makedirs(os.path.dirname(path), exist_ok=True)
header = f"# {date}\n\n> generated by {model}\n\n"
if os.path.exists(path):
    existing = open(path).read()
    open(path, 'w').write(existing + "\n---\n\n" + briefing)
else:
    open(path, 'w').write(header + briefing)
print(f"✅ ブリーフィング → memory/daily/{date}.md")
